---
title: "In-Class-Ex02: NKDE"
format:
  html: 
    code-fold: true
    code-summary: "Show the code"
execute:
  eval: true
  echo: true
  warning: false
  freeze: false
editor: visual
date: "`r Sys.Date()`"
---

Use the code chunk below to install and launch the 4 R packgaes

```{r}
pacman::p_load(sf, spNetwork, tmap, classInt, viridis, tidyverse)
```

## Data Import and Preparation

```{r}
network <- st_read(dsn="data", 
                   layer="Punggol_St")
childcare <- st_read(dsn="data", 
                   layer="Punggol_CC")
```

```{r}
str(network)
str(childcare)
```

```{r}
tmap_mode('view')
tm_shape(childcare) + 
  tm_dots() + 
  tm_shape(network) +
  tm_lines()
tmap_mode('plot')
```

## Network Constrained KDE (NetKDE) Analysis

```{r}
lixels <- lixelize_lines(network,
                         750,
                         mindist = 375)
```

```{r}
samples <- lines_center(lixels)
```

```{r}
densities <- nkde(network, 
                  events = childcare,
                  w = rep(1,nrow(childcare)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple", 
                  digits = 1, 
                  tol = 1,
                  grid_shape = c(1,1), 
                  max_depth = 8,
                  agg = 5, #we aggregate events within a 5m radius (faster calculation)
                  sparse = TRUE,
                  verbose = FALSE)
```

```{r}

```
